image: docker.nix-community.org/nixpkgs/cachix-flakes

build:
  variables:
    CACHIX_CACHE_NAME: gege251
  before_script:
    - cachix use "$CACHIX_CACHE_NAME"
  script:
    - cachix watch-exec $CACHIX_CACHE_NAME -- nix build .#checks.x86_64-linux.default -L
